import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react';

export interface Language {
  code: string;
  name: string;
  nativeName: string;
  flag: string;
}

export const LANGUAGES: Language[] = [
  { code: 'ru', name: 'Russian', nativeName: 'Русский', flag: '🇷🇺' },
  { code: 'en', name: 'English', nativeName: 'English', flag: '🇬🇧' },
  { code: 'es', name: 'Spanish', nativeName: 'Español', flag: '🇪🇸' },
  { code: 'zh', name: 'Chinese (Simplified)', nativeName: '中文 (简体)', flag: '🇨🇳' },
  { code: 'zh-TW', name: 'Chinese (Traditional)', nativeName: '中文 (繁體)', flag: '🇹🇼' },
  { code: 'de', name: 'German', nativeName: 'Deutsch', flag: '🇩🇪' },
  { code: 'fr', name: 'French', nativeName: 'Français', flag: '🇫🇷' },
  { code: 'ar', name: 'Arabic', nativeName: 'العربية', flag: '🇸🇦' },
  { code: 'pt', name: 'Portuguese', nativeName: 'Português', flag: '🇵🇹' },
  { code: 'it', name: 'Italian', nativeName: 'Italiano', flag: '🇮🇹' },
  { code: 'tr', name: 'Turkish', nativeName: 'Türkçe', flag: '🇹🇷' },
  { code: 'ja', name: 'Japanese', nativeName: '日本語', flag: '🇯🇵' },
  { code: 'ko', name: 'Korean', nativeName: '한국어', flag: '🇰🇷' },
  { code: 'uk', name: 'Ukrainian', nativeName: 'Українська', flag: '🇺🇦' },
  { code: 'hi', name: 'Hindi', nativeName: 'हिन्दी', flag: '🇮🇳' },
  { code: 'id', name: 'Indonesian', nativeName: 'Bahasa Indonesia', flag: '🇮🇩' },
  { code: 'vi', name: 'Vietnamese', nativeName: 'Tiếng Việt', flag: '🇻🇳' },
  { code: 'pl', name: 'Polish', nativeName: 'Polski', flag: '🇵🇱' },
  { code: 'nl', name: 'Dutch', nativeName: 'Nederlands', flag: '🇳🇱' },
  { code: 'fa', name: 'Persian', nativeName: 'فارسی', flag: '🇮🇷' },
  { code: 'th', name: 'Thai', nativeName: 'ไทย', flag: '🇹🇭' },
  { code: 'sv', name: 'Swedish', nativeName: 'Svenska', flag: '🇸🇪' },
  { code: 'cs', name: 'Czech', nativeName: 'Čeština', flag: '🇨🇿' },
  { code: 'ro', name: 'Romanian', nativeName: 'Română', flag: '🇷🇴' },
  { code: 'el', name: 'Greek', nativeName: 'Ελληνικά', flag: '🇬🇷' },
  { code: 'hu', name: 'Hungarian', nativeName: 'Magyar', flag: '🇭🇺' },
  { code: 'da', name: 'Danish', nativeName: 'Dansk', flag: '🇩🇰' },
  { code: 'fi', name: 'Finnish', nativeName: 'Suomi', flag: '🇫🇮' },
  { code: 'no', name: 'Norwegian', nativeName: 'Norsk', flag: '🇳🇴' },
  { code: 'he', name: 'Hebrew', nativeName: 'עברית', flag: '🇮🇱' },
  { code: 'ms', name: 'Malay', nativeName: 'Bahasa Melayu', flag: '🇲🇾' },
  { code: 'ur', name: 'Urdu', nativeName: 'اردو', flag: '🇵🇰' },
  { code: 'bg', name: 'Bulgarian', nativeName: 'Български', flag: '🇧🇬' },
  { code: 'sk', name: 'Slovak', nativeName: 'Slovenčina', flag: '🇸🇰' },
  { code: 'hr', name: 'Croatian', nativeName: 'Hrvatski', flag: '🇭🇷' },
  { code: 'sl', name: 'Slovenian', nativeName: 'Slovenščina', flag: '🇸🇮' },
  { code: 'lt', name: 'Lithuanian', nativeName: 'Lietuvių', flag: '🇱🇹' },
  { code: 'lv', name: 'Latvian', nativeName: 'Latviešu', flag: '🇱🇻' },
  { code: 'et', name: 'Estonian', nativeName: 'Eesti', flag: '🇪🇪' },
  { code: 'az', name: 'Azerbaijani', nativeName: 'Azərbaycanca', flag: '🇦🇿' },
  { code: 'kk', name: 'Kazakh', nativeName: 'Қазақша', flag: '🇰🇿' },
  { code: 'uz', name: 'Uzbek', nativeName: "O'zbekcha", flag: '🇺🇿' },
  { code: 'ka', name: 'Georgian', nativeName: 'ქართული', flag: '🇬🇪' },
  { code: 'hy', name: 'Armenian', nativeName: 'Հայերեն', flag: '🇦🇲' },
  { code: 'tl', name: 'Tagalog', nativeName: 'Tagalog', flag: '🇵🇭' },
  { code: 'bn', name: 'Bengali', nativeName: 'বাংলা', flag: '🇧🇩' },
  { code: 'sw', name: 'Swahili', nativeName: 'Kiswahili', flag: '🇰🇪' },
  { code: 'mn', name: 'Mongolian', nativeName: 'Монгол', flag: '🇲🇳' },
  { code: 'sr', name: 'Serbian', nativeName: 'Српски', flag: '🇸🇷' },
  { code: 'is', name: 'Icelandic', nativeName: 'Íslenska', flag: '🇮🇸' },
  { code: 'sq', name: 'Albanian', nativeName: 'Shqip', flag: '🇦🇱' },
];

const TRANSLATIONS: Record<string, Record<string, string>> = {
  ru: {
    'nav.trade': 'Торговля',
    'nav.gifts': 'Подарки',
    'nav.portfolio': 'Портфель',
    'nav.activity': 'Активность',
    'nav.profile': 'Профиль',
    'nav.deposit': 'Пополнить',
    'nav.withdraw': 'Вывести',
    'nav.settings': 'Настройки',
    'nav.workspace': 'Рабочая зона',
    'nav.account': 'Аккаунт',
    'nav.operational': 'Все системы работают',
    'nav.help': 'Центр помощи',
    
    'profile.title': 'Ваш профиль',
    'profile.subheading': 'Управление личными данными и настройками приложения.',
    'profile.personal_info': 'Личные данные',
    'profile.details': 'ДЕТАЛИ',
    'profile.preferences': 'НАСТРОЙКИ',
    'profile.settings': 'Настройки',
    'profile.user_id': 'ID пользователя',
    'profile.language': 'Язык интерфейса',
    'profile.platform': 'Платформа',
    'profile.trading_notif': 'Торговые уведомления',
    'profile.trading_notif_sub': 'Получать оповещения при исполнении ордеров',
    'profile.hide_small': 'Скрывать мелкие балансы',
    'profile.hide_small_sub': 'Скрывать активы стоимостью менее 1 GX',
    'profile.change_lang': 'Сменить язык',
    'profile.select_lang_title': 'Выберите язык',
    'profile.search_placeholder': 'Поиск языка...',
    'profile.no_languages': 'Язык не найден',

    'terminal.markets': 'Рынки',
    'terminal.live': 'В эфире',
    'terminal.search': 'Поиск подарков...',
    'terminal.balance': 'Баланс',
    'terminal.buy': 'Купить',
    'terminal.sell': 'Продать',
    'terminal.limit': 'Лимит',
    'terminal.market': 'Маркет',
    'terminal.stop': 'Стоп-Лимит',
    'terminal.order_book': 'Биржевой стакан',
    'terminal.recent_trades': 'Последние сделки',
    'terminal.price': 'Цена',
    'terminal.amount': 'Количество',
    'terminal.total': 'Итого',
    'terminal.open_orders': 'Открытые ордера',
    'terminal.trade_history': 'История торгов',
    'terminal.confirm': 'Подтвердить ордер',
    'terminal.chart': 'График',
    'terminal.no_orders': 'Нет активных ордеров',

    'capital.title': 'Telegram Подарки',
    'capital.subheading': 'Маркетплейс редких и коллекционных Telegram подарков',
    'capital.floor_price': 'Флор цена',
    'capital.volume': 'Объем (24ч)',
    'capital.items': 'Предметов',
    'capital.rarity': 'Редкость',
    'capital.buy_now': 'Купить сейчас',
    'capital.all_gifts': 'Все подарки',

    'portfolio.title': 'Ваш портфель',
    'portfolio.subheading': 'Обзор баланса, коллекции подарков и активов',
    'portfolio.total_value': 'Общая стоимость',
    'portfolio.my_gifts': 'Мои подарки',
    'portfolio.no_gifts': 'У вас пока нет купленных подарков',

    'transactions.title': 'История активности',
    'transactions.subheading': 'Лог всех сделок, пополнений и выводов средств',
    'transactions.all': 'Все',
    'transactions.trades': 'Сделки',
    'transactions.deposits': 'Пополнения',
    'transactions.withdrawals': 'Выводы',

    'dashboard.deposit_title': 'Пополнение баланса',
    'dashboard.withdraw_title': 'Вывод средств',
    'dashboard.amount': 'Сумма',
    'dashboard.confirm_deposit': 'Подтвердить пополнение',
    'dashboard.confirm_withdraw': 'Подтвердить вывод',
  },

  en: {
    'nav.trade': 'Trade',
    'nav.gifts': 'Gifts',
    'nav.portfolio': 'Portfolio',
    'nav.activity': 'Activity',
    'nav.profile': 'Profile',
    'nav.deposit': 'Deposit',
    'nav.withdraw': 'Withdraw',
    'nav.settings': 'Settings',
    'nav.workspace': 'Workspace',
    'nav.account': 'Account',
    'nav.operational': 'All systems operational',
    'nav.help': 'Help center',

    'profile.title': 'Your Profile',
    'profile.subheading': 'Manage your personal details and app settings.',
    'profile.personal_info': 'Personal Information',
    'profile.details': 'DETAILS',
    'profile.preferences': 'PREFERENCES',
    'profile.settings': 'Settings',
    'profile.user_id': 'User ID',
    'profile.language': 'Interface Language',
    'profile.platform': 'Platform',
    'profile.trading_notif': 'Trading Notifications',
    'profile.trading_notif_sub': 'Receive alerts when orders are filled',
    'profile.hide_small': 'Hide Small Balances',
    'profile.hide_small_sub': 'Hide assets worth less than 1 GX',
    'profile.change_lang': 'Change Language',
    'profile.select_lang_title': 'Select Language',
    'profile.search_placeholder': 'Search language...',
    'profile.no_languages': 'No languages found',

    'terminal.markets': 'Markets',
    'terminal.live': 'Live',
    'terminal.search': 'Search gifts...',
    'terminal.balance': 'Balance',
    'terminal.buy': 'Buy',
    'terminal.sell': 'Sell',
    'terminal.limit': 'Limit',
    'terminal.market': 'Market',
    'terminal.stop': 'Stop-Limit',
    'terminal.order_book': 'Order Book',
    'terminal.recent_trades': 'Recent Trades',
    'terminal.price': 'Price',
    'terminal.amount': 'Amount',
    'terminal.total': 'Total',
    'terminal.open_orders': 'Open Orders',
    'terminal.trade_history': 'Trade History',
    'terminal.confirm': 'Confirm Order',
    'terminal.chart': 'Chart',
    'terminal.no_orders': 'No open orders',

    'capital.title': 'Telegram Gifts',
    'capital.subheading': 'Marketplace of rare collectible Telegram gifts',
    'capital.floor_price': 'Floor Price',
    'capital.volume': 'Volume (24h)',
    'capital.items': 'Items',
    'capital.rarity': 'Rarity',
    'capital.buy_now': 'Buy Now',
    'capital.all_gifts': 'All Gifts',

    'portfolio.title': 'Your Portfolio',
    'portfolio.subheading': 'Overview of balance, gift collection and holdings',
    'portfolio.total_value': 'Total Value',
    'portfolio.my_gifts': 'My Gifts',
    'portfolio.no_gifts': 'No gifts owned yet',

    'transactions.title': 'Activity History',
    'transactions.subheading': 'Log of all trades, deposits, and withdrawals',
    'transactions.all': 'All',
    'transactions.trades': 'Trades',
    'transactions.deposits': 'Deposits',
    'transactions.withdrawals': 'Withdrawals',

    'dashboard.deposit_title': 'Deposit Funds',
    'dashboard.withdraw_title': 'Withdraw Funds',
    'dashboard.amount': 'Amount',
    'dashboard.confirm_deposit': 'Confirm Deposit',
    'dashboard.confirm_withdraw': 'Confirm Withdrawal',
  },

  es: {
    'nav.trade': 'Comerciar',
    'nav.gifts': 'Regalos',
    'nav.portfolio': 'Portafolio',
    'nav.activity': 'Actividad',
    'nav.profile': 'Perfil',
    'nav.deposit': 'Depositar',
    'nav.withdraw': 'Retirar',
    'nav.settings': 'Ajustes',
    'nav.workspace': 'Área de trabajo',
    'nav.account': 'Cuenta',
    'nav.operational': 'Sistemas operativos',
    'nav.help': 'Centro de ayuda',

    'profile.title': 'Tu Perfil',
    'profile.subheading': 'Gestiona tus datos personales y ajustes.',
    'profile.personal_info': 'Información Personal',
    'profile.details': 'DETALLES',
    'profile.preferences': 'PREFERENCIAS',
    'profile.settings': 'Ajustes',
    'profile.user_id': 'ID de Usuario',
    'profile.language': 'Idioma del Interfaz',
    'profile.platform': 'Plataforma',
    'profile.trading_notif': 'Notificaciones de trading',
    'profile.trading_notif_sub': 'Recibir alertas cuando se ejecuten las órdenes',
    'profile.hide_small': 'Ocultar saldos pequeños',
    'profile.hide_small_sub': 'Ocultar activos de valor inferior a 1 GX',
    'profile.change_lang': 'Cambiar idioma',
    'profile.select_lang_title': 'Seleccionar Idioma',
    'profile.search_placeholder': 'Buscar idioma...',
    'profile.no_languages': 'No se encontraron idiomas',

    'terminal.markets': 'Mercados',
    'terminal.live': 'En Vivo',
    'terminal.search': 'Buscar regalos...',
    'terminal.balance': 'Saldo',
    'terminal.buy': 'Comprar',
    'terminal.sell': 'Vender',
    'terminal.limit': 'Límite',
    'terminal.market': 'Mercado',
    'terminal.stop': 'Stop-Límite',
    'terminal.order_book': 'Libro de Órdenes',
    'terminal.recent_trades': 'Operaciones Recientes',
    'terminal.price': 'Precio',
    'terminal.amount': 'Cantidad',
    'terminal.total': 'Total',
    'terminal.open_orders': 'Órdenes Abiertas',
    'terminal.trade_history': 'Historial de Trading',
    'terminal.confirm': 'Confirmar Orden',
    'terminal.chart': 'Gráfico',
    'terminal.no_orders': 'Sin órdenes abiertas',

    'capital.title': 'Regalos de Telegram',
    'capital.subheading': 'Mercado de regalos coleccionables raros de Telegram',
    'capital.floor_price': 'Precio Mínimo',
    'capital.volume': 'Volumen (24h)',
    'capital.items': 'Artículos',
    'capital.rarity': 'Rareza',
    'capital.buy_now': 'Comprar Ahora',
    'capital.all_gifts': 'Todos los Regalos',

    'portfolio.title': 'Tu Portafolio',
    'portfolio.subheading': 'Resumen de saldo, colección de regalos y activos',
    'portfolio.total_value': 'Valor Total',
    'portfolio.my_gifts': 'Mis Regalos',
    'portfolio.no_gifts': 'Aún no posees regalos',

    'transactions.title': 'Historial de Actividad',
    'transactions.subheading': 'Registro de operaciones, depósitos y retiros',
    'transactions.all': 'Todo',
    'transactions.trades': 'Operaciones',
    'transactions.deposits': 'Depósitos',
    'transactions.withdrawals': 'Retiros',

    'dashboard.deposit_title': 'Depositar Fondos',
    'dashboard.withdraw_title': 'Retirar Fondos',
    'dashboard.amount': 'Monto',
    'dashboard.confirm_deposit': 'Confirmar Depósito',
    'dashboard.confirm_withdraw': 'Confirmar Retiro',
  },

  de: {
    'nav.trade': 'Handel',
    'nav.gifts': 'Geschenke',
    'nav.portfolio': 'Portfolio',
    'nav.activity': 'Aktivität',
    'nav.profile': 'Profil',
    'nav.deposit': 'Einzahlen',
    'nav.withdraw': 'Auszahlen',
    'nav.settings': 'Einstellungen',
    'nav.workspace': 'Arbeitsbereich',
    'nav.account': 'Konto',
    'nav.operational': 'Alle Systeme betriebsbereit',
    'nav.help': 'Hilfecenter',

    'profile.title': 'Ihr Profil',
    'profile.subheading': 'Verwalten Sie Ihre pers. Daten und Einstellungen.',
    'profile.personal_info': 'Persönliche Informationen',
    'profile.details': 'DETAILS',
    'profile.preferences': 'EINSTELLUNGEN',
    'profile.settings': 'Einstellungen',
    'profile.user_id': 'Benutzer-ID',
    'profile.language': 'Sprache',
    'profile.platform': 'Plattform',
    'profile.trading_notif': 'Handelsbenachrichtigungen',
    'profile.trading_notif_sub': 'Benachrichtigungen bei Ausführung erhalten',
    'profile.hide_small': 'Kleine Guthaben verbergen',
    'profile.hide_small_sub': 'Guthaben unter 1 GX ausblenden',
    'profile.change_lang': 'Sprache ändern',
    'profile.select_lang_title': 'Sprache auswählen',
    'profile.search_placeholder': 'Sprache suchen...',
    'profile.no_languages': 'Keine Sprachen gefunden',

    'terminal.markets': 'Märkte',
    'terminal.live': 'Live',
    'terminal.search': 'Geschenke suchen...',
    'terminal.balance': 'Guthaben',
    'terminal.buy': 'Kaufen',
    'terminal.sell': 'Verkaufen',
    'terminal.limit': 'Limit',
    'terminal.market': 'Markt',
    'terminal.stop': 'Stop-Limit',
    'terminal.order_book': 'Orderbuch',
    'terminal.recent_trades': 'Letzte Trades',
    'terminal.price': 'Preis',
    'terminal.amount': 'Menge',
    'terminal.total': 'Gesamt',
    'terminal.open_orders': 'Offene Aufträge',
    'terminal.trade_history': 'Handelsverlauf',
    'terminal.confirm': 'Auftrag bestätigen',
    'terminal.chart': 'Diagramm',
    'terminal.no_orders': 'Keine offenen Aufträge',

    'capital.title': 'Telegram Geschenke',
    'capital.subheading': 'Marktplatz für seltene Telegram-Geschenke',
    'capital.floor_price': 'Mindestpreis',
    'capital.volume': 'Volumen (24h)',
    'capital.items': 'Artikel',
    'capital.rarity': 'Seltenheit',
    'capital.buy_now': 'Jetzt kaufen',
    'capital.all_gifts': 'Alle Geschenke',

    'portfolio.title': 'Ihr Portfolio',
    'portfolio.subheading': 'Übersicht über Guthaben und Geschenkesammlung',
    'portfolio.total_value': 'Gesamtwert',
    'portfolio.my_gifts': 'Meine Geschenke',
    'portfolio.no_gifts': 'Noch keine Geschenke vorhanden',

    'transactions.title': 'Aktivitätsverlauf',
    'transactions.subheading': 'Protokoll aller Trades, Ein- und Auszahlungen',
    'transactions.all': 'Alle',
    'transactions.trades': 'Trades',
    'transactions.deposits': 'Einzahlungen',
    'transactions.withdrawals': 'Auszahlungen',

    'dashboard.deposit_title': 'Guthaben einzahlen',
    'dashboard.withdraw_title': 'Guthaben auszahlen',
    'dashboard.amount': 'Betrag',
    'dashboard.confirm_deposit': 'Einzahlung bestätigen',
    'dashboard.confirm_withdraw': 'Auszahlung bestätigen',
  },

  fr: {
    'nav.trade': 'Trader',
    'nav.gifts': 'Cadeaux',
    'nav.portfolio': 'Portefeuille',
    'nav.activity': 'Activité',
    'nav.profile': 'Profil',
    'nav.deposit': 'Déposer',
    'nav.withdraw': 'Retirer',
    'nav.settings': 'Paramètres',
    'nav.workspace': 'Espace de travail',
    'nav.account': 'Compte',
    'nav.operational': 'Tous les systèmes sont opérationnels',
    'nav.help': 'Centre d\'aide',

    'profile.title': 'Votre Profil',
    'profile.subheading': 'Gérez vos informations personnelles et vos paramètres.',
    'profile.personal_info': 'Informations personnelles',
    'profile.details': 'DÉTAILS',
    'profile.preferences': 'PRÉFÉRENCES',
    'profile.settings': 'Paramètres',
    'profile.user_id': 'ID Utilisateur',
    'profile.language': 'Langue de l\'interface',
    'profile.platform': 'Plateforme',
    'profile.trading_notif': 'Notifications de trading',
    'profile.trading_notif_sub': 'Recevoir des alertes lorsque les ordres sont exécutés',
    'profile.hide_small': 'Masquer les petits soldes',
    'profile.hide_small_sub': 'Masquer les actifs d\'une valeur inférieure à 1 GX',
    'profile.change_lang': 'Changer de langue',
    'profile.select_lang_title': 'Choisir la langue',
    'profile.search_placeholder': 'Rechercher une langue...',
    'profile.no_languages': 'Aucune langue trouvée',

    'terminal.markets': 'Marchés',
    'terminal.live': 'En direct',
    'terminal.search': 'Rechercher des cadeaux...',
    'terminal.balance': 'Solde',
    'terminal.buy': 'Acheter',
    'terminal.sell': 'Vendre',
    'terminal.limit': 'Limite',
    'terminal.market': 'Marché',
    'terminal.stop': 'Stop-Limite',
    'terminal.order_book': 'Carnet d\'ordres',
    'terminal.recent_trades': 'Transactions récentes',
    'terminal.price': 'Prix',
    'terminal.amount': 'Quantité',
    'terminal.total': 'Total',
    'terminal.open_orders': 'Ordres en cours',
    'terminal.trade_history': 'Historique des transactions',
    'terminal.confirm': 'Confirmer l\'ordre',
    'terminal.chart': 'Graphique',
    'terminal.no_orders': 'Aucun ordre en cours',

    'capital.title': 'Cadeaux Telegram',
    'capital.subheading': 'Marché de cadeaux Telegram rares et de collection',
    'capital.floor_price': 'Prix plancher',
    'capital.volume': 'Volume (24h)',
    'capital.items': 'Articles',
    'capital.rarity': 'Rareté',
    'capital.buy_now': 'Acheter maintenant',
    'capital.all_gifts': 'Tous les cadeaux',

    'portfolio.title': 'Votre Portefeuille',
    'portfolio.subheading': 'Aperçu du solde, de la collection et des actifs',
    'portfolio.total_value': 'Valeur totale',
    'portfolio.my_gifts': 'Mes cadeaux',
    'portfolio.no_gifts': 'Aucun cadeau possédé pour el moment',

    'transactions.title': 'Historique des activités',
    'transactions.subheading': 'Journal de toutes les transactions et dépôts',
    'transactions.all': 'Tout',
    'transactions.trades': 'Transactions',
    'transactions.deposits': 'Dépôts',
    'transactions.withdrawals': 'Retraits',

    'dashboard.deposit_title': 'Déposer des fonds',
    'dashboard.withdraw_title': 'Retirer des fonds',
    'dashboard.amount': 'Montant',
    'dashboard.confirm_deposit': 'Confirmer le dépôt',
    'dashboard.confirm_withdraw': 'Confirmer le retrait',
  },

  zh: {
    'nav.trade': '交易',
    'nav.gifts': '礼物',
    'nav.portfolio': '投资组合',
    'nav.activity': '活动历史',
    'nav.profile': '个人资料',
    'nav.deposit': '充值',
    'nav.withdraw': '提现',
    'nav.settings': '设置',
    'nav.workspace': '工作区',
    'nav.account': '账户',
    'nav.operational': '所有系统正常运行',
    'nav.help': '帮助中心',

    'profile.title': '个人资料',
    'profile.subheading': '管理您的个人信息和应用设置。',
    'profile.personal_info': '个人信息',
    'profile.details': '详细信息',
    'profile.preferences': '偏好设置',
    'profile.settings': '设置',
    'profile.user_id': '用户 ID',
    'profile.language': '界面语言',
    'profile.platform': '平台',
    'profile.trading_notif': '交易通知',
    'profile.trading_notif_sub': '订单成交时接收提醒',
    'profile.hide_small': '隐藏小额余额',
    'profile.hide_small_sub': '隐藏价值低于 1 GX 的资产',
    'profile.change_lang': '切换语言',
    'profile.select_lang_title': '选择语言',
    'profile.search_placeholder': '搜索语言...',
    'profile.no_languages': '未找到语言',

    'terminal.markets': '市场',
    'terminal.live': '实时',
    'terminal.search': '搜索礼物...',
    'terminal.balance': '余额',
    'terminal.buy': '买入',
    'terminal.sell': '卖出',
    'terminal.limit': '限价',
    'terminal.market': '市价',
    'terminal.stop': '止损限价',
    'terminal.order_book': '订单薄',
    'terminal.recent_trades': '最新成交',
    'terminal.price': '价格',
    'terminal.amount': '数量',
    'terminal.total': '总计',
    'terminal.open_orders': '当前委托',
    'terminal.trade_history': '交易历史',
    'terminal.confirm': '确认订单',
    'terminal.chart': '图表',
    'terminal.no_orders': '暂无挂单',

    'capital.title': 'Telegram 礼物',
    'capital.subheading': '稀有收藏级 Telegram 礼物交易市场',
    'capital.floor_price': '底价',
    'capital.volume': '24小时成交量',
    'capital.items': '商品数量',
    'capital.rarity': '稀有度',
    'capital.buy_now': '立即购买',
    'capital.all_gifts': '所有礼物',

    'portfolio.title': '您的投资组合',
    'portfolio.subheading': '总余额、礼物收藏与资产概览',
    'portfolio.total_value': '总价值',
    'portfolio.my_gifts': '我的礼物',
    'portfolio.no_gifts': '暂未拥有礼物',

    'transactions.title': '活动历史',
    'transactions.subheading': '所有交易、充值和提现记录',
    'transactions.all': '全部',
    'transactions.trades': '交易',
    'transactions.deposits': '充值',
    'transactions.withdrawals': '提现',

    'dashboard.deposit_title': '充值资金',
    'dashboard.withdraw_title': '提现资金',
    'dashboard.amount': '金额',
    'dashboard.confirm_deposit': '确认充值',
    'dashboard.confirm_withdraw': '确认提现',
  },

  tr: {
    'nav.trade': 'Ticaret',
    'nav.gifts': 'Hediyeler',
    'nav.portfolio': 'Portföy',
    'nav.activity': 'Aktivite',
    'nav.profile': 'Profil',
    'nav.deposit': 'Yatır',
    'nav.withdraw': 'Çek',
    'nav.settings': 'Ayarlar',
    'nav.workspace': 'Çalışma Alanı',
    'nav.account': 'Hesap',
    'nav.operational': 'Tüm sistemler çalışıyor',
    'nav.help': 'Yardım Merkezi',

    'profile.title': 'Profiliniz',
    'profile.subheading': 'Kişisel bilgilerinizi ve uygulama ayarlarınızı yönetin.',
    'profile.personal_info': 'Kişisel Bilgiler',
    'profile.details': 'DETAYLAR',
    'profile.preferences': 'TERCİHLER',
    'profile.settings': 'Ayarlar',
    'profile.user_id': 'Kullanıcı ID',
    'profile.language': 'Arayüz Dili',
    'profile.platform': 'Platform',
    'profile.trading_notif': 'Ticaret Bildirimleri',
    'profile.trading_notif_sub': 'Emirler gerçekleştiğinde uyarı al',
    'profile.hide_small': 'Küçük Bakiyeleri Gizle',
    'profile.hide_small_sub': '1 GX altındaki varlıkları gizle',
    'profile.change_lang': 'Dili Değiştir',
    'profile.select_lang_title': 'Dil Seçin',
    'profile.search_placeholder': 'Dil ara...',
    'profile.no_languages': 'Dil bulunamadı',

    'terminal.markets': 'Piyasalar',
    'terminal.live': 'Canlı',
    'terminal.search': 'Hediye ara...',
    'terminal.balance': 'Bakiye',
    'terminal.buy': 'Satın Al',
    'terminal.sell': 'Sat',
    'terminal.limit': 'Limit',
    'terminal.market': 'Piyasa',
    'terminal.stop': 'Stop-Limit',
    'terminal.order_book': 'Emir Defteri',
    'terminal.recent_trades': 'Son İşlemler',
    'terminal.price': 'Fiyat',
    'terminal.amount': 'Miktar',
    'terminal.total': 'Toplam',
    'terminal.open_orders': 'Açık Emirler',
    'terminal.trade_history': 'İşlem Geçmişi',
    'terminal.confirm': 'Emri Onayla',
    'terminal.chart': 'Grafik',
    'terminal.no_orders': 'Açık emir yok',

    'capital.title': 'Telegram Hediyeleri',
    'capital.subheading': 'Nadir koleksiyonluk Telegram hediyeleri pazarı',
    'capital.floor_price': 'Taban Fiyat',
    'capital.volume': 'Hacim (24s)',
    'capital.items': 'Öğeler',
    'capital.rarity': 'Nadirliğin',
    'capital.buy_now': 'Hemen Al',
    'capital.all_gifts': 'Tüm Hediyeler',

    'portfolio.title': 'Portföyünüz',
    'portfolio.subheading': 'Bakiye, hediye koleksiyonu ve varlıklara genel bakış',
    'portfolio.total_value': 'Toplam Değer',
    'portfolio.my_gifts': 'Hediyelerim',
    'portfolio.no_gifts': 'Henüz hediyeniz yok',

    'transactions.title': 'Aktivite Geçmişi',
    'transactions.subheading': 'Tüm işlemler, yatırımlar ve çekimler',
    'transactions.all': 'Tümü',
    'transactions.trades': 'İşlemler',
    'transactions.deposits': 'Yatırımlar',
    'transactions.withdrawals': 'Çekimler',

    'dashboard.deposit_title': 'Para Yatır',
    'dashboard.withdraw_title': 'Para Çek',
    'dashboard.amount': 'Miktar',
    'dashboard.confirm_deposit': 'Yatırmayı Onayla',
    'dashboard.confirm_withdraw': 'Çekimi Onayla',
  },

  uk: {
    'nav.trade': 'Торгівля',
    'nav.gifts': 'Подарунки',
    'nav.portfolio': 'Портфель',
    'nav.activity': 'Активність',
    'nav.profile': 'Профіль',
    'nav.deposit': 'Поповнити',
    'nav.withdraw': 'Вивести',
    'nav.settings': 'Налаштування',
    'nav.workspace': 'Робоча зона',
    'nav.account': 'Акаунт',
    'nav.operational': 'Усі системи працюють',
    'nav.help': 'Центр допомоги',

    'profile.title': 'Ваш профіль',
    'profile.subheading': 'Управління особистими даними та налаштуваннями.',
    'profile.personal_info': 'Особисті дані',
    'profile.details': 'ДЕТАЛІ',
    'profile.preferences': 'НАЛАШТУВАННЯ',
    'profile.settings': 'Налаштування',
    'profile.user_id': 'ID користувача',
    'profile.language': 'Мова інтерфейсу',
    'profile.platform': 'Платформа',
    'profile.trading_notif': 'Торгові сповіщення',
    'profile.trading_notif_sub': 'Отримувати сповіщення при виконанні ордерів',
    'profile.hide_small': 'Приховувати дрібні баланси',
    'profile.hide_small_sub': 'Приховувати активи вартістю менше 1 GX',
    'profile.change_lang': 'Змінити мову',
    'profile.select_lang_title': 'Оберіть мову',
    'profile.search_placeholder': 'Пошук мови...',
    'profile.no_languages': 'Мову не знайдено',

    'terminal.markets': 'Ринки',
    'terminal.live': 'У ефірі',
    'terminal.search': 'Пошук подарунків...',
    'terminal.balance': 'Баланс',
    'terminal.buy': 'Купити',
    'terminal.sell': 'Продати',
    'terminal.limit': 'Ліміт',
    'terminal.market': 'Маркет',
    'terminal.stop': 'Стоп-Ліміт',
    'terminal.order_book': 'Біржовий стакан',
    'terminal.recent_trades': 'Останні угоди',
    'terminal.price': 'Ціна',
    'terminal.amount': 'Кількість',
    'terminal.total': 'Усього',
    'terminal.open_orders': 'Відкриті ордери',
    'terminal.trade_history': 'Історія торгів',
    'terminal.confirm': 'Підтвердити ордер',
    'terminal.chart': 'Графік',
    'terminal.no_orders': 'Немає відкритих ордерів',

    'capital.title': 'Telegram Подарунки',
    'capital.subheading': 'Маркетплейс рідкісних колекційних Telegram подарунків',
    'capital.floor_price': 'Флор ціна',
    'capital.volume': 'Обсяг (24г)',
    'capital.items': 'Предметів',
    'capital.rarity': 'Рідкісність',
    'capital.buy_now': 'Купити зараз',
    'capital.all_gifts': 'Усі подарунки',

    'portfolio.title': 'Ваш портфель',
    'portfolio.subheading': 'Огляд балансу та колекції подарунків',
    'portfolio.total_value': 'Загальна вартість',
    'portfolio.my_gifts': 'Мої подарунки',
    'portfolio.no_gifts': 'У вас поки немає подарунків',

    'transactions.title': 'Історія активності',
    'transactions.subheading': 'Лог усіх угод, поповнень та виводів',
    'transactions.all': 'Усі',
    'transactions.trades': 'Угоди',
    'transactions.deposits': 'Поповнення',
    'transactions.withdrawals': 'Виводи',

    'dashboard.deposit_title': 'Поповнити баланс',
    'dashboard.withdraw_title': 'Вивести кошти',
    'dashboard.amount': 'Сума',
    'dashboard.confirm_deposit': 'Підтвердити поповнення',
    'dashboard.confirm_withdraw': 'Підтвердити вивід',
  },
};

interface LanguageContextType {
  currentLang: Language;
  setLanguage: (code: string) => void;
  t: (key: string, fallback?: string) => string;
  isLangModalOpen: boolean;
  openLangModal: () => void;
  closeLangModal: () => void;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [langCode, setLangCode] = useState<string>(() => {
    return localStorage.getItem('app_language') || 'ru';
  });
  const [isLangModalOpen, setIsLangModalOpen] = useState(false);

  useEffect(() => {
    localStorage.setItem('app_language', langCode);
  }, [langCode]);

  const setLanguage = (code: string) => {
    setLangCode(code);
  };

  const currentLang = LANGUAGES.find((l) => l.code === langCode) || LANGUAGES[0];

  const t = (key: string, fallback?: string): string => {
    // Try exact language dict
    const dict = TRANSLATIONS[langCode];
    if (dict && dict[key]) {
      return dict[key];
    }
    // Try English dict
    if (TRANSLATIONS.en && TRANSLATIONS.en[key]) {
      return TRANSLATIONS.en[key];
    }
    // Try Russian dict
    if (TRANSLATIONS.ru && TRANSLATIONS.ru[key]) {
      return TRANSLATIONS.ru[key];
    }
    return fallback || key;
  };

  return (
    <LanguageContext.Provider
      value={{
        currentLang,
        setLanguage,
        t,
        isLangModalOpen,
        openLangModal: () => setIsLangModalOpen(true),
        closeLangModal: () => setIsLangModalOpen(false),
      }}
    >
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
